module.exports = {
    'User': require('./user'),
    'Landlord': require('./landlord'),
    'Admin': require('./admin'),
    'Comment': require('./comment'),
    'Rent_Room_Detail': require('./rentroomdetail'),
    'Landlord_Receipt': require('./landlordreceipt'),
    'Room_Price': require('./roomprice'),
    'Room_Type': require('./roomtype'),
    'House': require('./house'),
    'Room': require('./room'),
    'Notifycation' : require('./notifycation'),
    'Room_Price': require('./roomprice'),
    'Room_Type' : require('./roomtype'),
    'Rating': require('./rating'),
    'AvgRating': require('./avgrating'),
    'Devices': require('./device'),
    'Province': require('./province'),
    'District': require('./district'),
    'Ward': require('./ward')
};
